FROM node:22-slim

RUN apt-get update -y && apt-get install -y openssl

# Enable pnpm (Corepack is included in Node.js 22, we just turn it on)
RUN corepack enable
# KEEP THIS CONSISTENT
WORKDIR /app

# 1. Install Dependencies
COPY package.json package-lock.json* ./

RUN pnpm install

# 2. Prisma Setup
COPY prisma ./prisma/
RUN npx prisma generate

# 3. Copy Code
COPY . .

EXPOSE 4000

# 4. Start Development Server
CMD ["pnpm", "run", "dev"]
